### ISSUE TITLE
Uses expired artifacts

### ISSUE THREAD

**Issue by azflin** [Rubilmax/foundry-gas-diff#100]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/10667203/211351906-ddaddd1e-8e33-4c47-87e7-5a1f08183a99.png">

When it searches for artifacts, it yields 2 results. The 1st result is not expired and the 2nd result is expired. It attempts to download the 2nd result, which results in "Artifact has expired" error.

**Comment by Rubilmax** [comment]
Hi! Thank you for your report.
You are using an outdated version of `foundry-gas-diff`: `3.7`
Newer versions are available, introducing a fix to the issue you raised. Please use for example the latest version: `3.13.2`

Closing this!
