### ISSUE TITLE
Looks like the report table format was updated

### ISSUE THREAD

**Issue by bluele** [Rubilmax/foundry-gas-diff#70]
ref. https://github.com/foundry-rs/foundry/pull/3666

It seems that this action is not working with the latest nightly.

**Comment by Rubilmax** [comment]
Thank you! I'll update it asap

**Comment by Rubilmax** [comment]
It is now working with the latest version v3.10. Can you confirm, pls?

**Comment by bluele** [comment]
hey @Rubilmax , thanks for your prompt fix! Looks good to me :+1:
